server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  # Now we need to configure our Api-Gateways Routes
  cloud:
    gateway:
      routes:     # Routes will contain the list of our Micro Services
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employeeService/**
        - id: DEPARTMENT-SERVICE
          # lb://______  Means the Load Balancer should balance the load for our Service name
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departmentService/**

eureka:
  client:
    register-with-eureka: true
    fatch-registry: true
    service-url:
      # Application Registry port
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
